In [249]:
import re

In [250]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [251]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [252]:
len(text)

205

In [253]:
num_characters = 34 #33 буквы + пробел

In [254]:
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [255]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [256]:
tokenizer.fit_on_texts(text)

In [257]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [258]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [259]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [260]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

199

In [261]:
import numpy as np

In [262]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [263]:
len(X)

199

In [264]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [265]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [266]:
from keras.layers import *
from keras.models import Sequential

In [267]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_15 (SimpleRNN)   (None, 500)               267500    
                                                                 
 dense_15 (Dense)            (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [268]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 11ms/step - loss: 3.3905 - accuracy: 0.0804
Epoch 2/100
7/7 [==============================] - 0s 11ms/step - loss: 2.3783 - accuracy: 0.3518
Epoch 3/100
7/7 [==============================] - 0s 11ms/step - loss: 1.9062 - accuracy: 0.4824
Epoch 4/100
7/7 [==============================] - 0s 11ms/step - loss: 1.5069 - accuracy: 0.5075
Epoch 5/100
7/7 [==============================] - 0s 12ms/step - loss: 1.2186 - accuracy: 0.6332
Epoch 6/100
7/7 [==============================] - 0s 13ms/step - loss: 1.0069 - accuracy: 0.6935
Epoch 7/100
7/7 [==============================] - 0s 10ms/step - loss: 0.9115 - accuracy: 0.7538
Epoch 8/100
7/7 [==============================] - 0s 12ms/step - loss: 0.7625 - accuracy: 0.8090
Epoch 9/100
7/7 [==============================] - 0s 11ms/step - loss: 0.6546 - accuracy: 0.8191
Epoch 10/100
7/7 [==============================] - 0s 11ms/step - loss: 0.5753 - accuracy: 0.8543
Epoch 11/100
7/7 [=

In [269]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [270]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 15ms/step
утренновтвве лу выйсопертгирой тоыетлизных тозулкинто п 


# Слова


In [389]:
with open('text.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '')

maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts([texts])

dist = list(tokenizer.word_counts.items())
data = tokenizer.texts_to_sequences([texts])
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)

data = tokenizer.texts_to_sequences([texts])
res = np.array( data[0] )

inp_words = 3
n = res.shape[0]-inp_words

X = np.array([res[i:i+inp_words] for i in range(n)])
Y = keras.utils.to_categorical(res[inp_words:], num_classes=maxWordsCount)

In [390]:
model = Sequential()
model.add(Embedding(maxWordsCount, 256, input_length = inp_words))
model.add(SimpleRNN(128, activation='tanh'))
model.add(Dense(maxWordsCount, activation='softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

history = model.fit(X, Y, batch_size=32, epochs=50)

Model: "sequential_34"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 3, 256)            256000    
                                                                 
 simple_rnn_33 (SimpleRNN)   (None, 128)               49280     
                                                                 
 dense_32 (Dense)            (None, 1000)              129000    
                                                                 
Total params: 434280 (1.66 MB)
Trainable params: 434280 (1.66 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/50
52/52 [==============================] - 1s 7ms/step - loss: 6.8576 - accuracy: 0.0361
Epoch 2/50
52/52 [==============================] - 0s 7ms/step - loss: 6.1921 - accuracy: 0.0559
Epoch 3/50
52/52 [==============================] - 0s 7ms/step - loss: 5.7106 - accu

In [391]:
def buildPhrase(texts, str_len = 10):
  res = texts
  data = tokenizer.texts_to_sequences([texts])[0]
  for i in range(str_len):
    x = data[i: i+inp_words]
    inp = np.expand_dims(x, axis=0)
    pred = model.predict( inp )
    indx = pred.argmax(axis=1)[0]
    data.append(indx)
    res += " " + tokenizer.index_word[indx]
  return res

for i in range(1):
  x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount)

res = buildPhrase("позитив добавляет годы")
print(res)

1/1 [==============================] - 0s 19ms/step
позитив добавляет годы свои вашей жизни лучшей двигаться прагматично оставайся вы узнаете других
